/// Translate English prefecture name to Japanese.
pub fn reverse_prefecture(en: &str) -> Option<&'static str> {
    match en {
        "Hokkaido" => Some("北海道"),
        "Aomori" => Some("青森県"),
        "Iwate" => Some("岩手県"),
        "Miyagi" => Some("宮城県"),
        "Akita" => Some("秋田県"),
        "Yamagata" => Some("山形県"),
        "Fukushima" => Some("福島県"),
        "Ibaraki" => Some("茨城県"),
        "Tochigi" => Some("栃木県"),
        "Gunma" => Some("群馬県"),
        "Saitama" => Some("埼玉県"),
        "Chiba" => Some("千葉県"),
        "Tokyo" => Some("東京都"),
        "Kanagawa" => Some("神奈川県"),
        "Niigata" => Some("新潟県"),
        "Toyama" => Some("富山県"),
        "Ishikawa" => Some("石川県"),
        "Fukui" => Some("福井県"),
        "Yamanashi" => Some("山梨県"),
        "Nagano" => Some("長野県"),
        "Gifu" => Some("岐阜県"),
        "Shizuoka" => Some("静岡県"),
        "Aichi" => Some("愛知県"),
        "Mie" => Some("三重県"),
        "Shiga" => Some("滋賀県"),
        "Kyoto" => Some("京都府"),
        "Osaka" => Some("大阪府"),
        "Hyogo" => Some("兵庫県"),
        "Nara" => Some("奈良県"),
        "Wakayama" => Some("和歌山県"),
        "Tottori" => Some("鳥取県"),
        "Shimane" => Some("島根県"),
        "Okayama" => Some("岡山県"),
        "Hiroshima" => Some("広島県"),
        "Yamaguchi" => Some("山口県"),
        "Tokushima" => Some("徳島県"),
        "Kagawa" => Some("香川県"),
        "Ehime" => Some("愛媛県"),
        "Kochi" => Some("高知県"),
        "Fukuoka" => Some("福岡県"),
        "Saga" => Some("佐賀県"),
        "Nagasaki" => Some("長崎県"),
        "Kumamoto" => Some("熊本県"),
        "Oita" => Some("大分県"),
        "Miyazaki" => Some("宮崎県"),
        "Kagoshima" => Some("鹿児島県"),
        "Okinawa" => Some("沖縄県"),
        _ => None,
    }
}

