/// Translate a Vision Framework English label to Japanese.
/// Returns the original label if no translation exists.
pub fn translate(label: &str) -> &str {
    match label {
        // ===== Nature / Scenery =====
        "sky" => "空",
        "blue_sky" => "青空",
        "night_sky" => "夜空",
        "cloud" | "cloudy" => "雲",
        "sunset" | "sunset_sunrise" => "夕焼け",
        "sunrise" => "朝焼け",
        "mountain" => "山",
        "hill" => "丘",
        "ocean" | "sea" | "water_body" => "海",
        "beach" | "shore" => "ビーチ",
        "lake" => "湖",
        "river" | "creek" | "waterways" => "川",
        "waterfall" => "滝",
        "water" | "liquid" => "水",
        "snow" | "frozen" => "雪",
        "rain" => "雨",
        "storm" => "嵐",
        "blizzard" => "吹雪",
        "fog" | "haze" => "霧",
        "rainbow" => "虹",
        "forest" | "jungle" => "森",
        "tree" | "branch" | "evergreen" | "sequoia"
        | "eucalyptus_tree" | "oak_tree" => "木",
        "maple_tree" => "紅葉",
        "palm_tree" => "ヤシの木",
        "willow" => "柳",
        "plant" | "vegetation" | "decorative_plant" => "植物",
        "flower" | "blossom" | "flower_arrangement" | "bouquet"
        | "begonia" | "carnation" | "dahlia" | "daisy" | "dandelion"
        | "cornflower" | "marigold" | "petunia"
        | "poinsettia" | "snapdragon" | "clover" | "holly"
        | "mistletoe" => "花",
        "rose" => "バラ",
        "sunflower" => "ひまわり",
        "chrysanthemum" => "菊",
        "tulip" => "チューリップ",
        "orchid" => "蘭",
        "lily" => "ユリ",
        "daffodil" => "水仙",
        "grass" | "foliage" | "shrub" | "ferns" | "moss" | "ivy" => "草",
        "garden" | "greenhouse" => "庭",
        "field" | "land" => "野原",
        "desert" | "sand_dune" => "砂漠",
        "volcano" => "火山",
        "island" => "島",
        "rock" | "rocks" | "cliff" | "megalith" => "岩",
        "sand" => "砂",
        "sun" => "太陽",
        "ice" => "氷",
        "wood_natural" => "自然木",
        "canyon" => "渓谷",
        "wetland" => "湿地",
        "acorn" => "どんぐり",
        "aurora" => "オーロラ",
        "bamboo" => "竹",
        "bonsai" => "盆栽",
        "cactus" => "サボテン",
        "cave" => "洞窟",
        "celestial_body" | "celestial_body_other" | "moon" => "天体",
        "geyser" => "間欠泉",
        "glacier" | "iceberg" => "氷河",
        "lava" | "embers" => "溶岩",
        "lightning" => "稲妻",
        "thunderstorm" => "雷雨",
        "tornado" => "竜巻",
        "nest" | "birdhouse" | "beehive" => "巣",
        "orchard" => "果樹園",
        "pond" => "池",
        "seaweed" => "海藻",
        "wheat" | "grain" => "麦",
        "mangrove" => "マングローブ",
        "coral_reef" => "サンゴ礁",
        "seed" => "種",
        "straw_hay" => "藁",

        // ===== Structures / Architecture =====
        "structure" => "構造物",
        "building" => "建物",
        "house" | "domicile" | "house_single" => "家",
        "apartment" => "マンション",
        "skyscraper" => "高層ビル",
        "temple" | "shrine" => "寺社",
        "church" => "教会",
        "castle" => "城",
        "ruins" => "遺跡",
        "bridge" => "橋",
        "arch" => "アーチ",
        "tower" | "clock_tower" | "belltower" => "塔",
        "dome" => "ドーム",
        "pyramid" => "ピラミッド",
        "monument" | "obelisk" => "記念碑",
        "statue" | "sculpture" | "gargoyle" => "彫刻",
        "stained_glass" => "ステンドグラス",
        "fountain" => "噴水",
        "fence" => "柵",
        "wall" => "壁",
        "roof" => "屋根",
        "stairs" | "escalator" => "階段",
        "door" | "portal" => "入口",
        "window" => "窓",
        "balcony" | "deck" | "patio" | "pergola" => "バルコニー",
        "tunnel" => "トンネル",
        "barn" => "納屋",
        "gazebo" => "東屋",
        "chimney" | "smokestack" => "煙突",
        "dam" => "ダム",
        "igloo" => "イグルー",
        "lighthouse" => "灯台",
        "pier" => "桟橋",
        "porch" => "ポーチ",
        "shed" | "silo" => "小屋",
        "shipyard" => "造船所",
        "windmill" | "wind_turbine" => "風車",
        "watermill" => "水車",
        "boathouse" => "ボートハウス",
        "porthole" => "舷窓",

        // ===== Location / Setting =====
        "outdoor" => "屋外",
        "indoor" | "interior_room" => "屋内",
        "urban" => "都市",
        "rural" | "agriculture" | "farm" | "vineyard" | "rice_field" => "田舎",
        "city" | "cityscape" => "街並み",
        "street" | "sidewalk" | "crosswalk" | "alley" => "通り",
        "road" | "highway" | "path" | "trail" | "road_other" | "dirt_road" => "道路",
        "park" => "公園",
        "playground" => "遊び場",
        "pool" | "swimming_pool" | "jacuzzi" => "プール",
        "stadium" | "arena" | "bleachers" => "スタジアム",
        "airport" => "空港",
        "train_station" | "station" | "railroad" | "track_rail" => "駅",
        "restaurant" => "レストラン",
        "bar" => "バー",
        "nightclub" => "クラブ",
        "shop" | "store" | "storefront" | "interior_shop" | "market" => "店",
        "museum" | "gallery" => "美術館",
        "school" | "classroom" => "学校",
        "hospital" => "病院",
        "health_club" => "ジム",
        "office" | "conference" | "cubicle" => "オフィス",
        "hotel" => "ホテル",
        "room" | "living_room" | "dining_room" | "kitchen_room" | "bathroom_room" => "部屋",
        "kitchen" | "kitchen_countertop" => "キッチン",
        "bathroom" | "bath" | "washbasin" | "bathroom_faucet" => "浴室",
        "bedroom" => "寝室",
        "library" | "bookshelf" => "図書館",
        "auditorium" | "theater" => "劇場",
        "aquarium" => "水族館",
        "zoo" => "動物園",
        "amusement_park" | "ferris_wheel" | "carousel" => "遊園地",
        "parking_lot" => "駐車場",
        "elevator" => "エレベーター",
        "dock" | "harbour" => "港",
        "driveway" => "車道",
        "garage" | "hangar" => "ガレージ",
        "cellar" => "地下室",
        "casino" => "カジノ",
        "circus" | "carnival" | "fairground" => "サーカス",
        "airshow" => "航空ショー",
        "atm" => "ATM",
        "manhole" => "マンホール",
        "rink" => "リンク",

        // ===== People =====
        "person" | "people" => "人物",
        "adult" => "大人",
        "teen" => "十代",
        "face" | "portrait" => "顔",
        "baby" | "infant" => "赤ちゃん",
        "child" | "kid" => "子供",
        "crowd" => "群衆",
        "selfie" => "自撮り",
        "bride" | "groom" | "wedding" | "wedding_dress" => "結婚式",
        "party" | "celebration" => "パーティー",
        "graduation" => "卒業式",
        "parade" => "パレード",
        "entertainer" | "singer" | "performance" => "パフォーマンス",
        "bridesmaid" => "ブライズメイド",
        "clown" => "ピエロ",

        // ===== Animals =====
        "animal" | "mammal" => "動物",
        "dog" | "basset" | "basenji" | "beagle" | "bichon" | "bulldog" | "chihuahua"
        | "collie" | "corgi" | "dachshund" | "dalmatian" | "doberman"
        | "german_shepherd" | "greyhound" | "husky" | "malamute" | "malinois"
        | "mastiff" | "newfoundland" | "pitbull" | "pomeranian" | "poodle"
        | "pug" | "retriever" | "ridgeback" | "rottweiler" | "schnauzer"
        | "setter" | "sheepdog" | "spaniel" | "terrier" | "vizsla"
        | "weimararer" | "irish_wolfhound" | "jack_russell_terrier"
        | "australian_shepherd" | "bernese_mountain" | "saint_bernard"
        | "hound" | "canine" | "weimaraner" => "犬",
        "cat" | "adult_cat" | "feline" => "猫",
        "kitten" => "子猫",
        "bird" | "gull" | "pigeon"
        | "cockatoo" | "dove" | "heron" | "hummingbird"
        | "parakeet" | "parrot" | "pelican" | "peregrine"
        | "puffin" | "raven" | "sandpiper" | "sparrow" | "stork" | "toucan"
        | "vulture" | "woodpecker" => "鳥",
        "penguin" => "ペンギン",
        "owl" => "フクロウ",
        "swan" => "白鳥",
        "eagle" => "鷲",
        "flamingo" => "フラミンゴ",
        "peacock" => "クジャク",
        "fish" | "puffer_fish" | "salmon"
        | "angelfish" | "clownfish" | "goldfish" | "guppy" | "lionfish"
        | "mackerel" | "seabass" | "snapper" | "sunfish" | "swordfish"
        | "trout" | "anchovy" | "sardine" => "魚",
        "koi" => "鯉",
        "shark" => "サメ",
        "tuna" => "マグロ",
        "stingray" => "エイ",
        "barracuda" => "バラクーダ",
        "horse" | "equestrian" | "saddle" => "馬",
        "insect" | "bug" => "虫",
        "butterfly" => "蝶",
        "pet" => "ペット",
        "deer" => "鹿",
        "cow" => "牛",
        "camel" => "ラクダ",
        "llama" => "リャマ",
        "elephant" => "象",
        "panda" => "パンダ",
        "rhinoceros" => "サイ",
        "rodent" => "げっ歯類",
        "shellfish" | "oyster" => "貝",
        "crab" => "カニ",
        "seafood" => "海鮮",
        "ungulates" => "有蹄類",
        "lion" => "ライオン",
        "tiger" => "虎",
        "cheetah" => "チーター",
        "leopard" => "ヒョウ",
        "alligator_crocodile" | "crocodile" => "ワニ",
        "ant" => "アリ",
        "arachnid" | "spider" => "クモ",
        "arthropods" => "節足動物",
        "badger" => "アナグマ",
        "barnacle" => "フジツボ",
        "bear" => "クマ",
        "bee" | "beekeeping" => "ハチ",
        "bison" | "boar" => "野牛",
        "bobcat" | "cougar" | "lynx" => "ヤマネコ",
        "caterpillar" => "毛虫",
        "centipede" | "millipede" => "ムカデ",
        "cephalopod" => "頭足類",
        "cetacean" | "dolphin" | "whale" => "イルカ・クジラ",
        "chameleon" | "gecko" | "iguana" | "lizard" | "monitor_lizard" => "トカゲ",
        "chinchilla" | "ferret" | "gerbil" | "hamster" => "小動物",
        "clam" | "conch" | "mussel" | "scallop" => "貝",
        "coyote_wolf" => "オオカミ",
        "donkey" => "ロバ",
        "dragonfly" => "トンボ",
        "elk" | "moose" => "ヘラジカ",
        "fox" => "キツネ",
        "frog" | "toad" => "カエル",
        "gastropod" | "snail" => "カタツムリ",
        "giraffe" => "キリン",
        "goat" => "ヤギ",
        "gorilla" => "ゴリラ",
        "hedgehog" => "ハリネズミ",
        "hippopotamus" => "カバ",
        "hyena" => "ハイエナ",
        "jellyfish" => "クラゲ",
        "kangaroo" => "カンガルー",
        "koala" => "コアラ",
        "ladybug" => "テントウムシ",
        "lemur" => "キツネザル",
        "lobster" => "ロブスター",
        "marsupial" => "有袋類",
        "mollusk" => "軟体動物",
        "moth" => "蛾",
        "octopus" => "タコ",
        "ostrich" => "ダチョウ",
        "otter" => "カワウソ",
        "pig" => "豚",
        "prairie_dog" => "プレーリードッグ",
        "porcupine" => "ヤマアラシ",
        "python" | "snake" | "snake_other" | "rattlesnake" => "ヘビ",
        "rabbit" => "ウサギ",
        "raccoon" => "アライグマ",
        "raptor" => "猛禽類",
        "rat" => "ネズミ",
        "reptile" => "爬虫類",
        "scarab" => "フンコロガシ",
        "scorpion" => "サソリ",
        "seahorse" => "タツノオトシゴ",
        "seal" | "sealion" => "アザラシ",
        "seashell" => "貝殻",
        "sheep" => "羊",
        "shrimp" => "エビ",
        "skunk" => "スカンク",
        "slug" => "ナメクジ",
        "spiderweb" => "クモの巣",
        "squirrel" => "リス",
        "starfish" => "ヒトデ",
        "tortoise" | "turtle" => "カメ",
        "walrus" => "セイウチ",
        "worm" => "ミミズ",
        "zebra" => "シマウマ",
        "urchin" => "ウニ",
        "dinosaur" => "恐竜",

        // ===== Food / Drink =====
        "food" | "meal" => "食べ物",
        "drink" | "beverage" | "juice" => "飲み物",
        "fruit" | "berry" | "citrus_fruit" | "apple" | "banana" | "mango" | "peach"
        | "strawberry" | "raspberry" | "lemon" | "lime" | "kiwi" => "果物",
        "vegetable" | "lettuce" | "tomato" | "broccoli" | "corn" | "potato"
        | "carrot" | "cucumber" | "asparagus" => "野菜",
        "dessert" | "sweet" | "frozen_dessert" | "ice_cream" => "デザート",
        "cake" | "birthday_cake" | "wedding_cake" | "cheesecake" | "muffin"
        | "cake_regular" => "ケーキ",
        "bread" | "baked_goods" | "croissant" | "white_bread" => "パン",
        "meat" | "steak" | "poultry" | "sausage" => "肉",
        "sushi" | "roe" => "寿司",
        "ramen" => "ラーメン",
        "spaghetti" | "pasta" => "パスタ",
        "tempura" => "天ぷら",
        "rice" => "ごはん",
        "soup" => "スープ",
        "salad" | "arugula" => "サラダ",
        "sandwich" | "hotdog" => "サンドイッチ",
        "hamburger" => "ハンバーガー",
        "fries" => "フライ",
        "egg" | "yolk" | "fried_egg" | "scrambled_eggs" | "omelet" => "卵",
        "stir_fry" | "cooking" => "料理",
        "falafel" | "springroll" => "揚げ物",
        "wasabi" | "seasonings" | "condiment" | "herb" | "cilantro" | "sesame" => "調味料",
        "coffee" => "コーヒー",
        "wine" | "alcohol" | "beer" | "liquor" | "red_wine" | "white_wine"
        | "sparkling_wine" | "tequila" => "酒",
        "candy" | "chocolate" => "お菓子",
        "cookie" => "クッキー",
        "chopsticks" => "箸",
        "antipasti" => "前菜",
        "avocado" => "アボカド",
        "bacon" => "ベーコン",
        "bagel" => "ベーグル",
        "baklava" => "バクラヴァ",
        "bean" | "green_beans" | "edamame" => "豆",
        "beef" => "牛肉",
        "beet" => "ビーツ",
        "biryani" => "ビリヤニ",
        "biscotti" | "biscuit" => "ビスケット",
        "blackberry" | "blueberry" | "cranberry" => "ベリー",
        "brownie" => "ブラウニー",
        "bruschetta" => "ブルスケッタ",
        "bubble_tea" => "タピオカ",
        "burrito" => "ブリトー",
        "butter" => "バター",
        "candy_cane" | "candy_other" => "キャンディ",
        "cantaloupe" | "honeydew" | "melon" => "メロン",
        "watermelon" => "スイカ",
        "caprese" => "カプレーゼ",
        "caramel" => "キャラメル",
        "cashew" | "macadamia" | "pecan" | "pistachio" | "peanut" | "nut" | "almond" => "ナッツ",
        "casserole" => "キャセロール",
        "cauliflower" => "カリフラワー",
        "celery" => "セロリ",
        "cereal" | "oatmeal" => "シリアル",
        "cheese" => "チーズ",
        "cherry" => "チェリー",
        "chestnut" => "栗",
        "chewing_gum" => "ガム",
        "chocolate_chip" => "チョコチップ",
        "chives" | "dill" | "rosemary" | "lemongrass" | "turmeric" | "spice" => "ハーブ",
        "cocktail" | "margarita" | "martini" | "mojito" | "sangria" => "カクテル",
        "coconut" => "ココナッツ",
        "coffee_bean" => "コーヒー豆",
        "coleslaw" => "コールスロー",
        "crepe" => "クレープ",
        "cupcake" => "カップケーキ",
        "curry" => "カレー",
        "daikon" => "大根",
        "donut" => "ドーナツ",
        "dumpling" | "gyoza" | "wonton" => "餃子",
        "durian" => "ドリアン",
        "eggplant" => "ナス",
        "fig" => "イチジク",
        "flan" => "プリン",
        "fondue" => "フォンデュ",
        "fried_chicken" => "フライドチキン",
        "fruitcake" => "フルーツケーキ",
        "garlic" => "ニンニク",
        "gingerbread" => "ジンジャーブレッド",
        "grape" => "ブドウ",
        "grapefruit" => "グレープフルーツ",
        "grilled_chicken" | "rotisserie" => "ローストチキン",
        "guacamole" => "ワカモレ",
        "guava" => "グアバ",
        "habanero" | "jalapeno" | "bell_pepper" | "pepper_veggie" => "ピーマン",
        "ham" | "salami" | "pepperoni" => "ハム",
        "honey" => "蜂蜜",
        "hummus" => "フムス",
        "jello" | "jelly" => "ゼリー",
        "kebab" | "satay" | "souvlaki" => "串焼き",
        "kohlrabi" => "コールラビ",
        "leek" => "ネギ",
        "lollipop" | "popsicle" => "キャンディ",
        "lychee" | "rambutan" | "mangosteen" => "ライチ",
        "mandarine" => "みかん",
        "oranges" => "オレンジ",
        "marshmallow" => "マシュマロ",
        "matzo" => "マッツァ",
        "meatball" => "ミートボール",
        "mushroom" => "キノコ",
        "mustard" => "マスタード",
        "naan" | "pita" | "tortilla" => "ナン",
        "nachos" | "quesadilla" | "taco" => "メキシカン",
        "nectarine" => "ネクタリン",
        "onion" => "タマネギ",
        "paella" => "パエリア",
        "pancake" | "waffle" => "パンケーキ",
        "papaya" => "パパイヤ",
        "passionfruit" => "パッションフルーツ",
        "pastry" => "ペストリー",
        "pea" => "エンドウ豆",
        "pear" => "梨",
        "persimmon" => "柿",
        "pickle" => "漬物",
        "pie" => "パイ",
        "pierogi" => "ピエロギ",
        "pineapple" => "パイナップル",
        "pizza" => "ピザ",
        "plum" => "プラム",
        "pomegranate" => "ザクロ",
        "popcorn" => "ポップコーン",
        "pretzel" => "プレッツェル",
        "pudding" => "プディング",
        "pumpkin" => "かぼちゃ",
        "quinoa" => "キヌア",
        "radish" => "ラディッシュ",
        "rhubarb" => "ルバーブ",
        "risotto" => "リゾット",
        "samosa" => "サモサ",
        "sauerkraut" => "ザワークラウト",
        "scone" => "スコーン",
        "shawarma" => "シャワルマ",
        "smoothie" => "スムージー",
        "soda" => "ソーダ",
        "souffle" => "スフレ",
        "spareribs" => "スペアリブ",
        "spinach" => "ホウレン草",
        "starfruit" => "スターフルーツ",
        "strudel" => "シュトゥルーデル",
        "tabbouleh" => "タブーレ",
        "taffy" => "タフィー",
        "tapas" => "タパス",
        "tapioca_pearls" => "タピオカ",
        "taro" => "タロイモ",
        "tea_drink" => "お茶",
        "teriyaki" => "照り焼き",
        "tiramisu" => "ティラミス",
        "yogurt" => "ヨーグルト",
        "zucchini" => "ズッキーニ",
        "apricot" => "杏",
        "artichoke" => "アーティチョーク",
        "milkshake" => "ミルクシェイク",
        "shellfish_prepared" => "貝料理",
        "sugar_cube" => "角砂糖",
        "sunflower_seeds" => "ひまわりの種",

        // ===== Tableware / Kitchen =====
        "table" => "テーブル",
        "tableware" | "plate" | "bowl" | "cup" | "mug" | "drinking_glass" => "食器",
        "utensil" | "spoon" | "fork" | "knife" | "cutting_board" => "食器",
        "cookware" | "pot_cooking" | "stove" | "grill" | "brick_oven" | "oven" => "調理器具",
        "cakestand" => "ケーキスタンド",
        "bottle" | "wine_bottle" => "ボトル",

        // ===== Furniture / Interior =====
        "furniture" => "家具",
        "chair" | "armchair" | "folding_chair" | "swivel_chair" | "chair_other" | "seat"
        | "stool" | "high_chair" | "bench" => "椅子",
        "sofa" => "ソファ",
        "chaise" => "寝椅子",
        "bed" | "bedding" | "pillow" => "ベッド",
        "desk" => "机",
        "cabinet" | "closet" => "棚",
        "curtain" => "カーテン",
        "lamp" | "chandelier" | "lamppost" | "spotlight" => "照明",
        "frame" => "額縁",
        "housewares" | "decoration" => "インテリア",
        "fireplace" => "暖炉",
        "straw_drinking" => "ストロー",
        "vase" => "花瓶",

        // ===== Transport =====
        "car" | "automobile" | "vehicle" | "suv"
        | "convertible" | "jeep" | "limousine" | "sportscar" => "車",
        "conveyance" => "乗り物",
        "train" | "train_real" | "streetcar" | "monorail" => "電車",
        "bus" | "van" | "motorhome" => "バス",
        "truck" => "トラック",
        "ambulance" => "救急車",
        "airplane" | "aircraft" => "飛行機",
        "boat" | "ship" | "watercraft" | "cruise_ship" | "sailboat"
        | "speedboat" | "houseboat" | "canoe" | "rowboat" | "barge" => "船",
        "bicycle" | "bike" | "cycling" | "tricycle" => "自転車",
        "motorcycle" | "scooter" | "atv" => "バイク",
        "tire" | "wheel" | "rim" => "タイヤ",
        "cart" | "shopping_cart" | "wheelbarrow" | "stroller" | "wagon" => "カート",
        "rickshaw" => "人力車",
        "bulldozer" | "backhoe" | "forklift" | "tractor" | "crane_construction" => "重機",
        "car_seat" => "チャイルドシート",
        "engine_vehicle" => "エンジン",
        "go_kart" => "ゴーカート",
        "mast" => "マスト",
        "oar" => "オール",
        "cableway" | "chairlift" | "tramway" => "ロープウェイ",
        "firetruck" => "消防車",
        "helicopter" => "ヘリコプター",
        "police_car" => "パトカー",
        "rocket" => "ロケット",
        "semi_truck" => "トレーラー",
        "snowmobile" => "スノーモービル",
        "submarine_water" => "潜水艦",
        "warship" => "軍艦",
        "yacht" => "ヨット",

        // ===== Clothing / Accessories =====
        "clothing" | "fashion" | "textile" => "ファッション",
        "kimono" => "着物",
        "jacket" | "hoodie" | "suit" | "tuxedo" | "gown" | "costume"
        | "sari" | "lab_coat" | "military_uniform" | "safety_vest"
        | "jeans" | "swimsuit" | "bathrobe" | "cloak" | "poncho" | "wetsuit"
        | "leotard" | "kilt" => "服",
        "hat" | "headgear" | "baseball_hat" | "sunhat" | "beanie" | "fedora" | "hardhat"
        | "cowboy_hat" | "sombrero" => "帽子",
        "shoes" | "footwear" | "sneaker" | "sandal" | "boot" | "ski_boot" | "high_heel"
        | "loafer" | "moccasin" => "靴",
        "eyeglasses" | "sunglasses" | "goggles" => "眼鏡",
        "scarf" | "necktie" | "bib" | "apron" => "アクセサリー",
        "purse" | "backpack" | "luggage" | "suitcase" | "bag" | "paper_bag" => "かばん",
        "umbrella" => "傘",
        "jewelry" => "ジュエリー",
        "tattoo" | "henna" => "タトゥー",
        "helmet" => "ヘルメット",
        "bowtie" => "蝶ネクタイ",
        "flipper" => "フィン",
        "ice_skates" => "スケート靴",
        "sock" => "靴下",
        "earmuffs" => "イヤーマフ",
        "glove" | "glove_other" | "mitten" => "手袋",

        // ===== Activities / Sports =====
        "sport" | "sports" | "sports_equipment" | "recreation" => "スポーツ",
        "concert" | "music" | "musical_instrument" | "speakers_music"
        | "drum" | "bongo_drum" | "organ_instrument" | "orchestra" => "音楽",
        "dance" | "dancing" | "breakdancing" | "samba" => "ダンス",
        "festival" | "matsuri" => "祭り",
        "ceremony" => "式典",
        "fireworks" | "pyrotechnics" | "sparkler" => "花火",
        "firecracker" => "爆竹",
        "travel" => "旅行",
        "hiking" => "ハイキング",
        "camping" | "tent" => "キャンプ",
        "swimming" | "watersport" => "水泳",
        "sunbathing" => "日光浴",
        "skiing" | "winter_sport" | "ski_equipment" | "snowboarding" | "snowboard"
        | "sledding" | "sled" | "skating" | "ice_skating" => "ウィンタースポーツ",
        "rock_climbing" => "ロッククライミング",
        "surfing" => "サーフィン",
        "fishing" => "釣り",
        "ballgames" | "baseball" | "tennis" | "racquet" => "球技",
        "games" | "chess" | "foosball" => "ゲーム",
        "workout" | "athletics" => "運動",
        "archery" => "アーチェリー",
        "badminton" => "バドミントン",
        "ballet" | "ballet_dancer" => "バレエ",
        "basketball" => "バスケ",
        "bellydance" => "ベリーダンス",
        "billiards" => "ビリヤード",
        "bodyboard" => "ボディボード",
        "bowling" => "ボウリング",
        "boxing" | "kickboxing" | "martial_arts" => "格闘技",
        "bungee" => "バンジー",
        "cheerleading" => "チアリーディング",
        "cricket_sport" => "クリケット",
        "diving" | "scuba" | "snorkeling" => "ダイビング",
        "dressage" | "jockey_horse" => "乗馬",
        "fencing_sport" => "フェンシング",
        "football" | "soccer" => "サッカー",
        "frisbee" => "フリスビー",
        "golf" | "golf_ball" | "golf_club" | "golf_course" => "ゴルフ",
        "gymnastics" => "体操",
        "hockey" => "ホッケー",
        "hula" => "フラダンス",
        "hurdle" => "ハードル",
        "jetski" => "ジェットスキー",
        "juggling" => "ジャグリング",
        "karaoke" => "カラオケ",
        "kayak" | "rafting" => "カヤック",
        "kiteboarding" | "windsurfing" | "wakeboarding" => "水上スポーツ",
        "motocross" | "motorsport" | "nascar" | "grand_prix" | "formula_one_car" => "モータースポーツ",
        "paintball" => "ペイントボール",
        "parasailing" | "parachute" | "hangglider" | "skydiving" => "スカイスポーツ",
        "ping_pong" => "卓球",
        "polo" => "ポロ",
        "rodeo" | "bullfighting" => "ロデオ",
        "rugby" => "ラグビー",
        "skateboard" | "skateboarding" | "skatepark" => "スケボー",
        "softball" => "ソフトボール",
        "squash_sport" => "スカッシュ",
        "sumo" => "相撲",
        "surfboard" => "サーフボード",
        "trampoline" => "トランポリン",
        "volleyball" | "waterpolo" => "バレーボール",
        "wrestling" => "レスリング",
        "yoga" => "ヨガ",
        "hunting" => "狩猟",
        "acrobat" => "アクロバット",
        "rollercoaster" => "ジェットコースター",
        "sandcastle" => "砂の城",
        "seesaw" | "swing_playground" | "slide_toy" => "遊具",
        "deejay" => "DJ",
        "ball" => "ボール",
        "baseball_bat" => "バット",
        "puck" => "パック",
        "putt" => "パット",
        "rollerskates" | "rollerskating" => "ローラースケート",
        "scoreboard" => "スコアボード",
        "podium" => "表彰台",

        // ===== Time / Lighting =====
        "night" | "nighttime" => "夜",
        "daytime" => "昼",
        "golden_hour" => "ゴールデンアワー",
        "dark" | "darkness" => "暗い",
        "bright" | "light" => "明るい",
        "fire" | "flame" => "火",

        // ===== Technology / Electronics =====
        "phone" | "smartphone" => "スマートフォン",
        "computer" | "laptop" | "computer_monitor" | "computer_keyboard" => "パソコン",
        "screen" | "monitor" | "television" => "画面",
        "camera" | "optical_equipment" | "tripod" => "カメラ",
        "consumer_electronics" | "circuit_board" => "電子機器",
        "electric_fan" | "appliance" | "refrigerator" => "家電",
        "drone_machine" => "ドローン",
        "headphones" => "ヘッドホン",
        "machine" => "機械",
        "computer_mouse" | "computer_tower" | "gamepad" | "joystick" => "パソコン周辺機器",
        "keypad" => "キーパッド",

        // ===== Music / Instruments =====
        "accordion" => "アコーディオン",
        "brass_music" => "金管楽器",
        "cello" => "チェロ",
        "clarinet" => "クラリネット",
        "flute" => "フルート",
        "guitar" => "ギター",
        "harp" => "ハープ",
        "microphone" => "マイク",
        "piano" => "ピアノ",
        "saxophone" => "サックス",
        "string_instrument" => "弦楽器",
        "tambourine" => "タンバリン",
        "trombone" => "トロンボーン",
        "trumpet" => "トランペット",
        "tuba" => "チューバ",
        "ukulele" => "ウクレレ",
        "violin" => "バイオリン",
        "woodwind" => "木管楽器",
        "xylophone" => "木琴",

        // ===== Objects =====
        "book" | "printed_page" => "本",
        "clock" | "watch" | "timepiece" | "dial"
        | "hourglass" | "sundial" | "stopwatch" => "時計",
        "sign" | "banner" | "billboards" | "street_sign" => "看板",
        "flag" | "flagpole" => "旗",
        "art" | "painting" | "artwork" | "illustrations" | "graffiti" => "アート",
        "toy" | "stuffed_animals" | "vehicle_toy" | "blocks" | "figurine"
        | "train_toy" => "おもちゃ",
        "gift" | "present" => "プレゼント",
        "document" | "paper" | "receipt" | "ticket" | "map" | "calendar"
        | "envelope" | "passport" | "magazine" | "newspaper" => "書類",
        "balloon" => "風船",
        "balloon_hotair" => "気球",
        "candle" | "candlestick" => "ろうそく",
        "christmas_tree" | "christmas_decoration" | "christmas" => "クリスマス",
        "halloween" => "ハロウィン",
        "handwriting" | "chalkboard" | "whiteboard" => "手書き",
        "origami" => "折り紙",
        "globe" => "地球儀",
        "trophy" => "トロフィー",
        "medal" => "メダル",
        "pen" | "office_supplies" => "文房具",
        "money" | "coin" | "currency" => "お金",
        "rope" | "cord" => "ロープ",
        "lifejacket" | "lifesaver" => "ライフジャケット",
        "screenshot" => "スクリーンショット",
        "container" | "basket_container" | "bucket" | "crate"
        | "carton" | "cardboard_box" => "容器",
        "abacus" => "そろばん",
        "axe" | "hammer" | "mallet" | "screwdriver" | "wrench" | "pliers"
        | "power_saw" | "chainsaw" => "工具",
        "barbell" | "dumbbell" => "ダンベル",
        "barrel" | "keg" => "樽",
        "binoculars" | "telescope" => "望遠鏡",
        "blender" | "juicer" | "microwave" | "dishwasher" | "toaster"
        | "toaster_oven" | "kitchen_oven" | "kitchen_faucet" | "kitchen_sink"
        | "laundry_machine" | "vacuum" => "家電",
        "board_game" | "backgammon" | "dice" | "domino" | "jigsaw"
        | "puzzles" | "play_card" | "poker" | "roulette" => "ボードゲーム",
        "briefcase" => "ブリーフケース",
        "broom" | "mop" => "ほうき",
        "cage" => "檻",
        "calculator" => "電卓",
        "caliper" | "measuring_tape" => "計測器具",
        "cassette" | "cd" | "diskette" | "record" => "メディア",
        "chart" | "diagram" | "flipchart" => "図表",
        "checkbook" | "credit_card" | "coupon" => "カード",
        "cigar" | "cigarette" | "smoking_item" => "タバコ",
        "clothesline" | "clothespin" => "洗濯物",
        "compass" => "コンパス",
        "corkscrew" => "コルク抜き",
        "crib" | "cradle" => "ベビーベッド",
        "dartboard" => "ダーツ",
        "decanter" | "jug" | "jar" | "kettle" | "teapot" | "thermos" => "容器",
        "doll" | "puppet" => "人形",
        "dragon_parade" => "龍舞",
        "easter_egg" => "イースターエッグ",
        "flashlight" => "懐中電灯",
        "gift_card" | "red_envelope" => "ギフトカード",
        "grater" | "ladle" | "spatula" | "whisk" | "rolling_pin"
        | "pan" | "steamer_cookware" => "調理器具",
        "hammock" => "ハンモック",
        "hookah" => "水タバコ",
        "iron_clothing" | "sewing" => "裁縫",
        "jack_o_lantern" => "ジャック・オ・ランタン",
        "kite" => "凧",
        "lantern" => "ランタン",
        "leash" => "リード",
        "license_plate" => "ナンバープレート",
        "light_bulb" => "電球",
        "lighter" | "matches" => "ライター",
        "mask" | "gas_mask" => "マスク",
        "medicine" | "stethoscope" | "syringe" | "crutch" | "stretcher" => "医療",
        "megaphone" => "メガホン",
        "microscope" => "顕微鏡",
        "mousetrap" => "ネズミ捕り",
        "mower" | "sprinkler" | "watering_can" | "rake" => "園芸",
        "paintbrush" | "easel" => "画材",
        "payphone" => "公衆電話",
        "piggybank" => "貯金箱",
        "pipe" => "パイプ",
        "printer" => "プリンター",
        "propeller" => "プロペラ",
        "pulley" | "winch" | "ratchet" | "gears" => "滑車",
        "santa_claus" => "サンタクロース",
        "scarecrow" => "かかし",
        "scissors" => "ハサミ",
        "skeleton" | "skull" => "骸骨",
        "snowball" | "snowman" | "snowshoe" => "雪遊び",
        "solar_panel" => "ソーラーパネル",
        "stereo" | "turntable" => "オーディオ",
        "sticky_note" => "付箋",
        "sword" => "剣",
        "tachometer" | "dashboard" | "thermostat" | "thermometer" => "計器",
        "terrarium" | "fishtank" | "fishbowl" => "水槽",
        "tiara" => "ティアラ",
        "toolbox" => "工具箱",
        "trash_can" => "ゴミ箱",
        "treadmill" => "ルームランナー",
        "typewriter" => "タイプライター",
        "videogame" => "ビデオゲーム",
        "wallet" => "財布",
        "weight_scale" => "体重計",
        "wreath" => "リース",
        "yarn" => "毛糸",
        "hydrant" => "消火栓",
        "extinguisher" => "消火器",
        "traffic_light" => "信号機",
        "bell" => "鐘",
        "mailbox" => "郵便受け",
        "anvil" => "金床",
        "horseshoe" => "蹄鉄",
        "pole" | "pylon" => "ポール",
        "sack" => "袋",
        "tool" => "工具",
        "media" => "メディア",
        "cosmetic_tool" => "化粧道具",
        "disco_ball" => "ミラーボール",
        "road_safety_equipment" => "交通安全設備",

        // ===== Materials =====
        "material" => "素材",
        "wood_processed" => "木材",
        "brick" => "レンガ",
        "raw_glass" => "ガラス",
        "polka_dots" => "水玉",

        // ===== Misc / Photography =====
        "landscape" => "風景",
        "scenery" => "景色",
        "panorama" => "パノラマ",
        "abstract" => "抽象",
        "texture" => "テクスチャ",
        "pattern" => "パターン",
        "colorful" => "カラフル",
        "black_and_white" | "monochrome" => "モノクロ",
        "blurry" | "blur" => "ぼけ",
        "closeup" | "macro" => "接写",
        "aerial" => "空撮",
        "underwater" => "水中",
        "reflection" => "反射",
        "shadow" => "影",
        "silhouette" => "シルエット",
        "symmetric" | "symmetry" => "対称",
        "vintage" | "retro" => "レトロ",
        "snow_covered" => "雪景色",
        "grave" => "墓",
        "rangoli" => "ランゴリ",
        "diorama" => "ジオラマ",
        "shower" => "シャワー",
        "toilet_seat" => "トイレ",
        "diaper" | "pacifier" => "赤ちゃん用品",
        "wheelchair" => "車椅子",

        // No translation available
        other => other,
    }
}
